### PR TITLE
Updated footer for inside form pages to use minimal global footer

### PR DESCRIPTION
**Pull request by anselmbradford**
## Changes

- Updated footer for inside form pages to use minimal global footer.

## Testing

- `gulp build`
- Internal form pages should have a minimal footer. Resizing the window to small size should show a return to top button.

## Review

- @niqjohnson 

## Screenshots

Desktop:
screen shot 2016-06-14 at 4 52 41 pm

Small screen:
screen shot 2016-06-15 at 9 32 54 am

### CODE REVIEW

**Comment by anselmbradford** [comment]
@kurzn with Nic out, would you want to sign off on this based on the screenshots?

**Comment by higs4281** [comment]
👍 footers with flags show up for me, and "back to the top" appears at about viewport 600.

Should there be a flag in the footer of the landing page?

**Comment by anselmbradford** [comment]
@higs4281 Thanks for the review! No, this should just be the internal form pages. The header/footer of the landing page are being left at the moment.

**Comment by kurzn** [comment]
@anselmbradford I'm sending over an updated "comp" in a bit. Please hold :) We need to add some more info to the footer.

**Comment by kurzn** [comment]
Footer should look like this crude mockup (use existing footer styles/conventions)

Both links launch modals, which we will tackle in a sep GH issue.

image

**Comment by anselmbradford** [comment]
Using existing global footer styles as much as possible I end up with:

screen shot 2016-06-15 at 2 34 55 pm

The spacing seems pretty loose, but that's global footer settings. Is that workable, or should I override those. Also the vertical bar not extending all the way down is a global footer issue. We could fake it extending down here if that would be better?

Here's mobile:
screen shot 2016-06-15 at 2 36 11 pm

**Comment by kurzn** [comment]
I have no issues with the desktop spacing. Not ideal, but also not worth monkeying with. For mobile, can we add more vertical space between the links? The live area around them is not tall enough for a touch screen.

**Comment by anselmbradford** [comment]
> The live area around them is not tall enough for a touch screen.

Hmm, yeah, I was thinking that's how it was but there are mobile styles on the live site for mobile that aren't being applied. I'll see why not.

**Comment by anselmbradford** [comment]
@kurzn mobile updated:

screen shot 2016-06-16 at 9 35 18 am

**Comment by anselmbradford** [comment]
Single paragraph for contact blurb:

screen shot 2016-06-16 at 9 51 39 am

screen shot 2016-06-16 at 9 51 27 am

**Comment by anselmbradford** [comment]
Ready for review again

**Comment by anselmbradford** [comment]
screen shot 2016-06-16 at 9 57 32 am

**Comment by kurzn** [comment]
Bingo! 👍

**Pull request merged**
