### PR TITLE
Updated header for inside pages to use minimal header

### PR DESCRIPTION
**Pull request by anselmbradford**
## Removes

- Unneeded `block` styles.

## Changes

- Updated header for inside form pages to use minimal global header.
- Imports Capital Framework and overrides unsupported fieldset styles.
- Visually hides annotation toggle link by making it invisible.

## Testing

- `gulp build` visit the inside form pages and note header and changed type hierarchy and button styles.

## Review

- @niqjohnson 

## Screenshots

screen shot 2016-06-13 at 5 33 03 pm

## Notes

- To toggle the annotations you will need to hover over the upper-left corner of the page till the cursor turns into a hand. The link is still there, it's just invisible now. Heads up @niqjohnson @kurzn @caheberer

### CODE REVIEW

**Comment by niqjohnson** [comment]
The header is looking great. Two things I think we can clean up before we merge.

First, can we make the annotations link visible again? I'm not sure how widely that's used outside of our team, so I'm hesitant to hide it just in case someone we don't know about is depending on it. I think we can move it around if it interferes with anything in the new header, though.

Second, it looks like Capital Framework introduced some style bugs on a few of the pages. Here are the biggest ones I've found so far:

#### Spacing between the last form field and the button well is missing in all steps

spacing

#### The "select files to upload" button is de-centered in step 3

files

#### The new company city and state fields are floating weirdly in step 4

boarding-state

#### The city and state fields for the identification options are also floating weirdly in step 4

account-state

#### Some links are double underlined and floating weirdly in step 6

links

Other than the city/state floating weirdness, I'm not sure if any of those fixes should hold up getting this merged and the header released. @caheberer, what do you think?

**Comment by anselmbradford** [comment]
> First, can we make the annotations link visible again? I'm not sure how widely that's used outside of our team, so I'm hesitant to hide it just in case someone we don't know about is depending on it. I think we can move it around if it interferes with anything in the new header, though.

So the whole sidebar looks like it's built to expect the toggle be fixed at the upper-left. When visible it ends up looking like:

screen shot 2016-06-13 at 2 07 55 pm

I hid it since that can be communicated to the immediate team and doesn't require dev time to re-tailor the sidebar, but I'm unclear how widely the annotations are used. I thought it was just our immediate team?

**Comment by caheberer** [comment]
I agree with @niqjohnson 

> Other than the city/state floating weirdness, I'm not sure if any of those fixes should hold up getting this merged and the header released.

**Comment by niqjohnson** [comment]
@anselmbradford: What if we changed "Open annotations" and "Toggle annotations" to just "Notes"? That makes the link short enough on a typical laptop screen to keep it from overlapping any of the header but still keeps some kind of a link visible in case anyone is expecting it.

**Comment by anselmbradford** [comment]
@niqjohnson I fixed all the noted issues.
In regard to the annotations, what about an ⎗ and ⎘ icon? It fits nicely:

screen shot 2016-06-14 at 2 10 42 pm

screen shot 2016-06-14 at 2 10 50 pm

**Comment by niqjohnson** [comment]
👍 

Looks awesome!

**Pull request merged**
